Bigeco/Invaders

src/engine/DrawManager.java, src/screen/RecoveryScreen.java
=> Revert "feat: edit drawRecoveryMenu method"

src/engine/DrawManager.java
=> Revert "style: change the position of the sentence and numbers"

src/engine/Core.java, src/engine/DrawManager.java, src/screen/EnhanceScreen.java, src/screen/SkinStoreScreen.java
- add method: drawCircleLine, drawCircleFill, drawEnhanceStoneString
Centerd and Both Side circle line and filling method to implement an enhanced page.
drawEnhanceStoneString Method shows the number of reinforcement stones, area range, and damage values
- change method: drawEnhanceMenu
- change Class: EnhanceScreen
Defined variables for drawCircleLine and drawCircleFill. (x, y width, height) and Used drawCircleLine, drawCircleFill
- change comment
=> merge: origin and fature/enhance_weapon branch

src/engine/Core.java
Game level control after recovery
=> feat: edit recovery gameState in Core.java

src/engine/Core.java
quit during the game(after recovery)
=> feat: edit Recovery  in Core.javaFeature/recovery

src/engine/Core.java, src/engine/DrawManager.java, src/engine/EnhanceManager.java, src/engine/GameSettings.java, src/screen/GameScreen.java
- Number of enhance stone increases When acquired from the game screen
- Number of coin increases When acquired from the game screen
- Coin count location changed
- Add annotation
=> feat: number of enhance stone increases When acquired from the game screen

src/engine/Core.java, src/engine/DrawManager.java
add String Coin and change color
=> feat: edit drawRecoveryConfirmPage 

src/engine/Core.java, src/engine/DrawManager.java, src/screen/RecoveryPaymentScreen.java
=> feat: add coin object in RecoveryPaymentScreen method

src/engine/Core.java
Issue | #151 
> The screen was complicated so I changed the screen size.
=> SI-24 feat: change size of screen (x1.1)

src/engine/DrawManager.java
Issue | resolves #158 
**1. text color : white > green, yellow**
_I changed the 'Stage Clear' text from its original white color to green, and 'COIN : ' text from its original white color to yellow._
**2. game time text format : 00.000 > 00:00.000**
_I changed the game runtime display format from '00.000' to '00:00.000'._
**3. text position**
_I changed the position of the 'Stage Clear' text._
=> SI-11 design: change the color and position of the clear text

src/engine/Core.java, src/engine/DrawManager.java, src/screen/EnhanceScreenRecovery.java
Issue | resolve #176 
The following elements have changed: 
1. subMenu Index 
(before) ItemStore, Enhancement, Continue, SkinStore
(After) Enhancement, Continue
2. Method naming
(before) RecoverySubMenu
(After) DrawRecoverySubMenu
3. Modify Core.java
- Add function
- Delete unnecessary returnCode(ex.7) according recorrecting index
=> SI-16 Enhance after recovery

src/engine/DrawManager.java, src/engine/GameState.java, src/screen/StoreScreen.java
Issue | resolves #166 
Describe
1. add string : coinMsg
I added coinMsg to indicate the message when the coin is running low.
2. make draw method : printCoinMsg
I added printCoinMsg to draw a message when the coin is running low.
=> feat: add message if player has not enough coins

src/engine/DrawManager.java, src/screen/SkinStoreScreen.java
Issue | resolves #164
Describe
1. skin store: add message
I added printCoinMsg to the skinstore to draw a message when there is a shortage of coins.
=> "feat: add coin message in skinstore"

src/effect/Effect.java, src/effect/ShipEffect.java, src/engine/BGM.java, src/engine/Core.java, src/engine/CountUpTimer.java, src/engine/DrawManager.java, src/engine/EnhanceManager.java, src/engine/ItemManager.java, src/engine/SoundEffect.java, src/entity/EnemyShipFormation.java, src/entity/Ship.java, src/screen/EnhanceScreen.java, src/screen/EnhanceScreen_2P.java, src/screen/GameScreen.java, src/screen/GameScreen_2P.java, src/screen/HighScoreScreen.java, src/screen/RandomBoxScreen.java, src/screen/RandomBoxScreen_2P.java, src/screen/SkinStoreScreen.java, src/screen/StageSelectScreen.java, src/screen/StoreScreen.java, src/screen/StoreScreen_2P.java, src/screen/TwoPlayHighScoreScreen.java
Issue | resolves #209 (1)
**Unconventional variable names have been renamed.**
_Unconventional variable names have been renamed._
=> SI-66 refactor: rename non-conventional variable names

src/effect/Effect.java, src/effect/ShipEffect.java, src/engine/BGM.java, src/engine/Core.java, src/engine/CountUpTimer.java, src/engine/DrawManager.java, src/engine/EnhanceManager.java, src/engine/ItemManager.java, src/engine/SoundEffect.java, src/entity/EnemyShipFormation.java, src/entity/Ship.java, src/screen/EnhanceScreen.java, src/screen/EnhanceScreen_2P.java, src/screen/GameScreen.java, src/screen/GameScreen_2P.java, src/screen/HighScoreScreen.java, src/screen/RandomBoxScreen.java, src/screen/RandomBoxScreen_2P.java, src/screen/SkinStoreScreen.java, src/screen/StageSelectScreen.java, src/screen/StoreScreen.java, src/screen/StoreScreen_2P.java, src/screen/TwoPlayHighScoreScreen.java
Reverts SI-66 refactor: rename non-conventional variable names #210
=> Revert "SI-66 refactor: rename non-conventional variable names"

src/effect/Effect.java, src/effect/ShipEffect.java, src/engine/BGM.java, src/engine/Core.java, src/engine/CountUpTimer.java, src/engine/DrawManager.java, src/engine/EnhanceManager.java, src/engine/GameState.java, src/engine/GameState_2P.java, src/engine/ItemManager.java, src/engine/SoundEffect.java, src/entity/EnemyShipFormation.java, src/entity/Item.java, src/entity/ItemPool.java, src/entity/Laser.java, src/entity/Ship.java, src/screen/EnhanceScreen.java, src/screen/EnhanceScreen_2P.java, src/screen/GameScreen.java, src/screen/GameScreen_2P.java, src/screen/RandomBoxScreen.java, src/screen/RandomBoxScreen_2P.java, src/screen/SkinStoreScreen.java, src/screen/StageSelectScreen.java, src/screen/StoreScreen.java, src/screen/StoreScreen_2P.java, src/screen/SubMenuScreen_2P.java, src/screen/TwoPlayHighScoreScreen.java
Issue | resolves #215 (1)
**1. Unconventional variable names have been renamed.**
_Unconventional variable names have been renamed._
=> SI-66 refactor: rename unconventional variable names

src/effect/ShipEffect.java
Issue | resolves #217
I fixed an issue where multiple bullets were fired when shooting once.
=> SI-217 fix: fix multiple bullets were fired

src/engine/Core.java, src/engine/DrawManager.java, src/entity/EnemyShipFormation.java, src/screen/RandomRewardScreen.java, src/screen/RandomRewardScreen_2P.java
Issue | resolves #219
Describe
The following elements have changed
1. unused private field: remove
I've removed the unnecessary and unused private field.
=> refactor: remove unused private field

src/engine/BGM.java, src/engine/Core.java, src/engine/DrawManager.java, src/engine/GameState.java, src/engine/GameState_2P.java, src/engine/SoundEffect.java, src/entity/EnemyShipFormation.java, src/entity/Item.java, src/entity/Laser.java, src/screen/EnhanceScreen_2P.java, src/screen/GameScreen.java, src/screen/GameScreen_2P.java, src/screen/HighScoreScreen.java, src/screen/RecoveryPaymentScreen_2P.java, src/screen/StoreScreen_2P.java, src/screen/TwoPlayHighScoreScreen.java, src/screen/TwoPlayScoreScreen.java
Issue | resolves #221 (1)
**1. Method and variable names that do not follow convention have been renamed.**
_Unconventional method and variable names were renamed in all files._
=> SI-66 refactor: rename unconventional method names

src/effect/ShipEffect.java, src/engine/DrawManager.java, src/entity/EnemyShipFormation.java, src/entity/Item.java, src/entity/Laser.java, src/entity/Ship.java, src/screen/StageSelectScreen.java, test/scoreColorTest.java, test/slowlyChangingColorsTest.java
Issue | resolves #221 (1)
**1. method name : drawCoin > drawCoinCount**
_You can see that this is a method that shows the number of coins._
=> SI-66 refactor: rename unconventional method and variable names

src/screen/GameScreen.java
Issue | resolves #153 (1)
**Add enhanced sound for bulletY**
_Added  enhanced sound when attacking with bulletY during reinforcement._
=> SI-39 feature: add enhanced sound for bulletY
